#!/bin/bash
# Instructions to push to GitHub
# Run these commands in your terminal

echo "=========================================="
echo "Push CoordFinder to GitHub"
echo "=========================================="
echo ""
echo "Repository: https://github.com/aieuren/coordfinder"
echo ""
echo "Choose one of these methods:"
echo ""
echo "----------------------------------------"
echo "METHOD 1: Using GitHub CLI (Recommended)"
echo "----------------------------------------"
echo "gh auth login"
echo "cd /workspaces/workspaces"
echo "git push -u origin main"
echo ""
echo "----------------------------------------"
echo "METHOD 2: Using SSH Key"
echo "----------------------------------------"
echo "# First, add your SSH key to GitHub:"
echo "# 1. Generate key: ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "# 2. Copy key: cat ~/.ssh/id_ed25519.pub"
echo "# 3. Add to GitHub: https://github.com/settings/keys"
echo ""
echo "cd /workspaces/workspaces"
echo "git push -u origin main"
echo ""
echo "----------------------------------------"
echo "METHOD 3: Using Personal Access Token"
echo "----------------------------------------"
echo "# 1. Create token at: https://github.com/settings/tokens"
echo "# 2. Select scopes: repo (all)"
echo "# 3. Copy the token"
echo ""
echo "cd /workspaces/workspaces"
echo "git remote set-url origin https://github.com/aieuren/coordfinder.git"
echo "git push -u origin main"
echo "# Username: aieuren"
echo "# Password: <paste-your-token>"
echo ""
echo "----------------------------------------"
echo "METHOD 4: Using Git Credential Helper"
echo "----------------------------------------"
echo "cd /workspaces/workspaces"
echo "git config credential.helper store"
echo "git remote set-url origin https://github.com/aieuren/coordfinder.git"
echo "git push -u origin main"
echo "# Enter your GitHub username and Personal Access Token"
echo ""
echo "=========================================="
echo "Current Status:"
echo "=========================================="
cd /workspaces/workspaces
echo "Branch: $(git branch --show-current)"
echo "Commit: $(git log --oneline -1)"
echo "Remote: $(git remote get-url origin)"
echo "Files ready to push: 11 files, 2750 lines"
echo ""
echo "After successful push, visit:"
echo "https://github.com/aieuren/coordfinder"
